version: "3.0"

services:
  app:
    image: "fastpai-app:1.0"
    container_name: "app"
    volumes:
      - "./volumes/data:/var/lib/postgresql/data"

  db:
    image: "postgres:12.1-alpine"
    container_name: "db"
    volumes:
      - "./volumes/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"
